# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Matthew E. Denson
title: In My Mind
email: matthew@densons.org
description: >- # this means to ignore newlines until "baseurl:"
  A blog about my current projects and reading.
baseurl: "" # the subpath of your site, e.g. /blog
environment: production
google_analytics: UA-161518205-1
url: "https://matthew.densons.org" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
permalink: /blog/:categories/:year/:month/:day/:title.html
excerpt_separator: <!--more-->

exclude:
  - Gemfile
  - Gemfile.lock
  - docker
  - Makefile
  - .env
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
